### ISSUE TITLE
Issues with multiple quests (Vanilla)

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#109]
I believe most of those issues appeared in the past few version and they are true for the last official release.

Currently I am leveling a new character on Vanilla and I have noticed that some quests are not displayed properly on minimap.

(If you need in-game screenshots, I can provide those as well.)

1. After I have completed [Bashal'Aran](https://classicdb.ch/?quest=956) and turned it in, the next quest still shows me on minimap, which mob drops [Ancient Moonstone Seal](https://classicdb.ch/?item=5338) though there should only be a marker for an object that allows to destroy it.
2. There are numerous Beached Sea Turtle/Beached Sea Creature quests in Darkshore (nine in total). Once you pick up one of those, the other quest with the same title disappear from map. And after you turn the quest in, the one you turned in will once again appear on the map which is not really helpful.
3. [Raedon Duskstriker](https://classicdb.ch/?npc=14725) offers quests to turn-in cloth for Darnassus reputation. pfQuest displays the available quest as "Unknown".
4. After you fulfil the requirements for [One Shot. One Kill](https://classicdb.ch/?quest=5713) the available quest marker is still on the map.
5. [Trek to Ashenvale](https://classicdb.ch/?quest=990) not showing on minimap while NPC offers it. (This is a new issue I have not noticed before pfQuest 5.0. Most of the time it is cured by typing /run ReloadUI(), but some quests will not appear on minimap even after that.)
6. Once I arrived to Stonetalon Mountains, pfQuest informed me that quest [Covert Ops - Alpha](https://classicdb.ch/?quest=1079) is available. However, it is part of a chain and you cannot pick it up.
7. pfQuest does not know about [Young Crocolisk Skins](https://classicdb.ch/?quest=484) or at least will not display it on minimap even after UI reload.
8. [Ambassador Berrybuck](https://classicdb.ch/?npc=271) does not offer any quests. However, pfQuest believes that at level 26 he will offer a quest Ambushed In The Forest. [The only mention](https://quests.extreme-gaming.de/quest,191,world-of-warcraft---azeroth---duskwood---ambushed-in-the-forest--neutral-.html) of this quest that I found is in German. No database actually lists it.
9. After I have done [Eight-Legged Menaces](https://classicdb.ch/?quest=245) pfQuest informed that there is a new Unknown quest available from [Watcher Dobbs](https://classicdb.ch/?npc=888). Apparently there is some quest that never made it into the game, but made its way into some databases. Personally I have seen one private server where an extra quest was available, but it was completely broken.
10. [An Old History Book](https://classicdb.ch/?item=2794) from Duskwood strats a chain that leads to Southshore. Once I turned in the quest to NPC in Stormwind, he offered me the follow-up [Soutshore](https://classicdb.ch/?quest=538). pfQuest does not display the available quest on minimap.

P.S. Is it possible to not display quests that you do not meet skill requirements for? E.g. [Moonglow Vest](https://classicdb.ch/?quest=1582) is only available once you hit 90 in Leatherworking.

**Comment by nonameform** [comment]
11. [Sentinel Melyria Frostshadow](https://classicdb.ch/?npc=3880) and [Illiyana](https://classicdb.ch/?npc=3901) are shown in a wrong place on minimap. This is their position in TBC, not in Vanilla.

**Comment by shagu** [comment]
Thanks for your detailled feedback. I will look into it one by one and report back if I have any further questions.

**Comment by shagu** [comment]
> 1. After I have completed Bashal'Aran and turned it in, the next quest still shows me on minimap, which mob drops Ancient Moonstone Seal though there should only be a marker for an object that allows to destroy it.

pfQuest did by accident show items that are provided for a quest as a objective. It is fixed with this commit: https://github.com/shagu/pfQuest/commit/f0f1f6dd8cd7494ca0989b9121fd00d8d4569aef

> 2. There are numerous Beached Sea Turtle/Beached Sea Creature quests in Darkshore (nine in total). Once you pick up one of those, the other quest with the same title disappear from map. And after you turn the quest in, the one you turned in will once again appear on the map which is not really helpful.

There are now QuestIDs accessible in vanilla, so this works via guessing based on the name and the quest text. I have improved the detection and tested with those quests.
On my tests, all quest-ids where properly detected now. Fixed by the following commits:
https://github.com/shagu/pfQuest/commit/299a338b34456c5dfa1269f918d8d8bdb685cbba https://github.com/shagu/pfQuest/commit/055ab55a532a898b495054619e59958a25943004 https://github.com/shagu/pfQuest/commit/ba0c0a572fee071ee1824de3eb038477e215a6b2 https://github.com/shagu/pfQuest/commit/93efed9dc80cedc4b9efdda68ff5649c97efad1a

> 3. Raedon Duskstriker offers quests to turn-in cloth for Darnassus reputation. pfQuest displays the available quest as "Unknown".

pfQuest did show incomplete quests (also ones that don't have a name). From now on, only quests that have a name will be shown. Fixed by this commit:
https://github.com/shagu/pfQuest/commit/fd2fdf586cc4af91cf70bcaf3e252c688827b480

> 4. After you fulfil the requirements for One Shot. One Kill the available quest marker is still on the map.

pfQuest's titles come from the VMaNGOS database, I have seen that CMaNGOS is using a different title for that quest. It now tries to find the best title based on levenshtein algorithm in order to detect a quest-ID for the quest. Also remade the quest tracking and history in order to use quest-ids instead of names as much as possible. Fixed by the following commits:
https://github.com/shagu/pfQuest/commit/72d638190326847758dd25132544081f612973ed https://github.com/shagu/pfQuest/commit/1e91d5b0cf99f47d1798bd8201303b0bb983251b https://github.com/shagu/pfQuest/commit/74374e902d2b9e5f7e61ea86eea5bf64a18cdd5f https://github.com/shagu/pfQuest/commit/82daae65d09514c6fa107732279419e69f24880d https://github.com/shagu/pfQuest/commit/1b6ffbd5cd74da9c8631694121bc74c44e5f1f9a https://github.com/shagu/pfQuest/commit/84a4bff4c0c6e6fddb56a5f56245fd1bcfb2b707 https://github.com/shagu/pfQuest/commit/69db753ced5f0fee2fe9bf64285e26327382b739

> 5. Trek to Ashenvale not showing on minimap while NPC offers it. (This is a new issue I have not noticed before pfQuest 5.0. Most of the time it is cured by typing /run ReloadUI(), but some quests will not appear on minimap even after that.)

The NPC "Sentinel Selarin" is spawned via a script and therefore the pfQuest extractors didn't catch it. I have manually added an entry for it now. Fixed by this commit:

https://github.com/shagu/pfQuest/commit/54e3f22233d3d89313b00cecb7b91cce3ea42f7f

> 6. Once I arrived to Stonetalon Mountains, pfQuest informed me that quest Covert Ops - Alpha is available. However, it is part of a chain and you cannot pick it up.

There is an issue with the pre-quest detection right now. It's tracked in this ticket: https://github.com/shagu/pfQuest/issues/98

> 7. pfQuest does not know about Young Crocolisk Skins or at least will not display it on minimap even after UI reload.

I can't reproduce that one. It displays fine for me.

> 8. Ambassador Berrybuck does not offer any quests. However, pfQuest believes that at level 26 he will offer a quest Ambushed In The Forest. The only mention of this quest that I found is in German. No database actually lists it.

Since this is a valid quest that exists on servers that perform a full progression, I'm unsure if I should really remove that one. It's a quest that got removed again before 1.12 hit. It would frustrate those who play on lower patch versions. I need some time to think about it.

> 9. After I have done Eight-Legged Menaces pfQuest informed that there is a new Unknown quest available from Watcher Dobbs. Apparently there is some quest that never made it into the game, but made its way into some databases. Personally I have seen one private server where an extra quest was available, but it was completely broken.

Probably the same as in 3.) and should also be fixed by https://github.com/shagu/pfQuest/commit/fd2fdf586cc4af91cf70bcaf3e252c688827b480

> 10. An Old History Book from Duskwood strats a chain that leads to Southshore. Once I turned in the quest to NPC in Stormwind, he offered me the follow-up Soutshore. pfQuest does not display the available quest on minimap.

The problem was, that the Southshore quest is flagged as level 38 quest with a minimum of 20. The addon did hide the quest, as the level is more than 10 levels above the player. However, it will no longer hide quests which have a min-level that is below the player, not matter how high-level the quest is. Fixed by: https://github.com/shagu/pfQuest/commit/26ce10b564506b5be5303fb55c737526ea2e16ae

> 11. Sentinel Melyria Frostshadow and Illiyana are shown in a wrong place on minimap. This is their position in TBC, not in Vanilla.

Do you have sources for that? Wrong positions are something that should be reported to the wow server databases (VMaNGOS/CMaNGOS) so that it can be corrected there. 
To me it looks accurate though, because pfQuest shows the same positions as on classic wowhead: https://de.classic.wowhead.com/npc=3901/illiyana

**Comment by shagu** [comment]
PS: Please not that I have not built a release yet. Due to the deep changes from quest-titles to quest-IDs it might can cause lags and/or errors. I'll be going to use it as is for a while to see if anything pops up. If it's running smooth, I will add a new tag for it.

**Comment by nonameform** [comment]
Thank you for taking the time to check every issue!

As for issue 11, it seems that AoWoW DB lists the wrong location. I had to do a little investigation to report an error to Kronos as well, since their NPC placement is the same as in TBC. Classic Wowhead is correct (as proved by Thottbot from 2006-2007).

**Comment by nonameform** [comment]
I have just ran into an issue with _Beached Sea Turtle_ (https://classicdb.ch/?quest=4731 and https://classicdb.ch/?quest=4732) quests. When I picked up the item for 4732, there was an exclamation mark on the map. After turning-in the quest, the mark was still there, so I removed it manually with shift-click.

I checked WTF and according to the file I have completed three quests with the same title from other part of Darkshore, even though I have not been there yet (https://classicdb.ch/?quest=4723, https://classicdb.ch/?quest=4725 and https://classicdb.ch/?quest=4727). Once I changed quest ids in WTF to the proper ones, the quests at the bottom of the map disappeared instead.

It seems to me that the problem I described in my first post is still present. Also I have noticed in DB browser that three of Beached Sea quests are marked as both Alliance and Horde, which is of course not true. All quests in Darkshore are Alliance only.

**Comment by nonameform** [comment]
Also I have noticed that quest _One Shot, One Kill_ still shows up on my map as exclamation mark, even though I have completed the requirements. I have reported that one before as number 4.

**Comment by nonameform** [comment]
pfQuest will not display Young Crocolisk Skins on minimap or on tooltip for quest giver. Number 7 on my list.

![WoWScrnShot_021021_135622](https://user-images.githubusercontent.com/34381716/107504046-cb572e00-6bab-11eb-886c-d4fd095f0282.jpg)

**Comment by shagu** [comment]
> I have just ran into an issue with _Beached Sea Turtle_ (https://classicdb.ch/?quest=4731 and https://classicdb.ch/?quest=4732) quests. When I picked up the item for 4732, there was an exclamation mark on the map. After turning-in the quest, the mark was still there, so I removed it manually with shift-click.

I can't reproduce that. I just went to quest 4732, accepted it and the exclamation mark was removed and updated properly.
I repeated this 10 times, without any updating issue. Please note, if you search in browser for a quest, it will show the starter symbol as "!" and the ender as "?", always. No matter if you already did it or not. Browser nodes are not modified by the tracking system and are handled seperately. Use `/db clean` to clear up custom browser searches.

> I checked WTF and according to the file I have completed three quests with the same title from other part of Darkshore, even though I have not been there yet (https://classicdb.ch/?quest=4723, https://classicdb.ch/?quest=4725 and https://classicdb.ch/?quest=4727). Once I changed quest ids in WTF to the proper ones, the quests at the bottom of the map disappeared instead.

I was not able to reproduce this. Shift-clicking a quest marker on the map does **only** delete the assigned quest ID, not by name. Deleting all quests with the same name was an old behaviour changed months ago. Just watch `/db journal` while clicking the Beached Sea Creature quests and you'll see. I did it quite some times on the quests you mentioned and only one quest was marked each time.

> It seems to me that the problem I described in my first post is still present. Also I have noticed in DB browser that three of Beached Sea quests are marked as both Alliance and Horde, which is of course not true. All quests in Darkshore are Alliance only.

Related to: https://github.com/shagu/pfQuest/issues/128

> Also I have noticed that quest One Shot, One Kill still shows up on my map as exclamation mark, even though I have completed the requirements. I have reported that one before as number 4.

Looks like there was a regression when i introduced levenshtein detection limits in order to resolve freezes on custom quests.
It has now been reworked again: https://github.com/shagu/pfQuest/commit/4b28c652c6d2ecc01c329f94fefa785e0c98acb6 https://github.com/shagu/pfQuest/commit/f44e0106ad509595969b95c16424e372d0ba21f9 

There was also an issue within the questgiver update function, that didn't resolve server quest names on the map. It now updates questgivers based on internal database and the server quest names with this commit: https://github.com/shagu/pfQuest/commit/63ce32c54f96dfe18dd94f2e9b6b7402123c71bb

> pfQuest will not display Young Crocolisk Skins on minimap or on tooltip for quest giver. Number 7 on my list.

After completing [Daily Delivery](https://classicdb.ch/?quest=469) (which is listed as a pre-quest of it), it shows up just fine for me. It isn't a prequest on CMaNGOS based servers, so if you think the pre-quest is wrong, please provide a bugtracker entry with evidence to the [VMaNGOS issue tracker](https://github.com/vmangos/core/issues), to have it automatically fixed with the next pfQuest database update.

Latest pfQuest version is now `6.3`

**Comment by nonameform** [comment]
Little stupid me did not check Kronos DB for _Beached Sea Creature_ quests. They are using different IDs, so that is why pfQuest "acts" weird (just one example https://classicdb.ch/?quest=4723 vs. https://vanilla-twinhead.twinstar.cz/?quest=4723).

As for pre-quest for _Young Crocolisk Skins_: I cannot find any mention of it besides classicdb.ch. Neither Thottbot, nor old Wowhead ([TBC era comment though](https://www.wowhead.com/quest=469/daily-delivery#comments:id=137598)), nor Classic Wowhead mentions Daily Delivery as a pre-quest. I believe that this particular requirement listed at classicdb.ch might be wrong. Usually there would be a comment from someone who is not able to pick up the quest as there is a pre-requirement for it, but I was unable to find any.

**Comment by nonameform** [comment]
Oh, by the way. Beached Sea Creature location for 4723 is actually right at Kronos, not at classicdb.ch (https://www.wowhead.com/quest=4723/beached-sea-creature#comments:id=13794).

I will check all locations later at Thottbot.

**Comment by nonameform** [comment]
All quests besides one are mixed up at classicdb.ch:

4722
[classicdb](https://classicdb.ch/?quest=4722), [thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4722), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4722) - 37,62 (the only proper location)

4723
[classicdb](https://classicdb.ch/?quest=4723) - 36,70 (4728 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4723), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4723) - 41,31

4725
[classicdb](https://classicdb.ch/?quest=4725) - 32,80 (4730 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4725), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4725) - 44,20

4727
[classicdb](https://classicdb.ch/?quest=4725) - 31,83 (4731 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4727), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4727) - 53,18

4728
[classicdb](https://classicdb.ch/?quest=4728) - 31,85 (4732 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4728), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4728) - 36,70

4730
[classicdb](https://classicdb.ch/?quest=4730) - 31,87 (4733 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4730), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4730) - 32,80

4731
[classicdb](https://classicdb.ch/?quest=4731) - 41,31 (4723 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4731), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4731) - 31,83

4732
[classicdb](https://classicdb.ch/?quest=4732) - 44,20 (4725 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4732), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4732) - 31,85

4733
[classicdb](https://classicdb.ch/?quest=4733) - 53,18 (4727 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4733), [kronos](https://vanilla-twinhead.twinstar.cz/?quest=4733) - 31,87
